# Generated by Django 3.2.9 on 2021-12-05 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_servico_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='position',
            name='criados',
        ),
        migrations.RemoveField(
            model_name='position',
            name='modificado',
        ),
        migrations.RemoveField(
            model_name='service',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='service',
            name='criados',
        ),
        migrations.RemoveField(
            model_name='service',
            name='modificado',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='criados',
        ),
        migrations.RemoveField(
            model_name='team',
            name='modificado',
        ),
        migrations.AddField(
            model_name='position',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='position',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='team',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='team',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
